#! /bin/bash

# random plain batch_norm_True_residual_False_seed_0 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --res --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --res --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --res --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --res --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_True_seed_0 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_0_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 0 --device 0 --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_False_seed_123456 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --res --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --res --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --res --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --res --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_True_seed_123456 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123456_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123456 --device 0 --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_False_seed_123 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --res --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --res --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --res --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --res --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_True_seed_123 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_123_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 123 --device 0 --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_False_seed_2023 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --res --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --res --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --res --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_False_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --res --distance 1 --steps 40 --norm layer --random normal

# random plain batch_norm_True_residual_True_seed_2023 device 0; change distance
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 0.05 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 0.5 --steps 40 --norm layer --random normal
python loss-lens-ResNet-cifar10.py --model '/global/cfs/cdirs/m636/geniesse/ResNet20_models/resnet20_batch_norm_True_residual_True_seed_2023_net.pkl' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/ResNet20_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 1 --steps 40 --norm layer --random normal

