#! /bin/bash

# # random plain cifar10 seed 0 device 0; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 0 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 0 --device 0 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 0 --device 0 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 0 --device 0 --distance 3 --steps 40 --norm layer --random normal

# # random plain cifar10c seed 0 device 0; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 0 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 0 --device 0 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 0 --device 0 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_0_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 0 --device 0 --distance 3 --steps 40 --norm layer --random normal

# # random plain cifar10 seed 123 device 1; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123 --device 1 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123 --device 1 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123 --device 1 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123 --device 1 --distance 3 --steps 40 --norm layer --random normal

# # random plain cifar10c seed 123 device 1; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123 --device 1 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123 --device 1 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123 --device 1 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123 --device 1 --distance 3 --steps 40 --norm layer --random normal

# # random plain cifar10 seed 123456 device 2; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123456 --device 2 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123456 --device 2 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123456 --device 2 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --batch 512 --seed 123456 --device 2 --distance 3 --steps 40 --norm layer --random normal

# # random plain cifar10c seed 123456 device 2; change distance
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123456 --device 2 --distance 0.1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123456 --device 2 --distance 0.3 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123456 --device 2 --distance 1 --steps 40 --norm layer --random normal
# python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_123456_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --corrupted --batch 512 --seed 123456 --device 2 --distance 3 --steps 40 --norm layer --random normal

# random plain cifar10 seed 2023 device 3; change distance
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 0.3 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 1 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{00}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --batch 512 --seed 2023 --device 0 --distance 3 --steps 40 --norm layer --random normal

# random plain cifar10c seed 2023 device 3; change distance
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --corrupted --batch 512 --seed 2023 --device 0 --distance 0.1 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --corrupted --batch 512 --seed 2023 --device 0 --distance 0.3 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --corrupted --batch 512 --seed 2023 --device 0 --distance 1 --steps 40 --norm layer --random normal
python loss-lens-Vit-cifar10.py --model '/global/cfs/cdirs/m636/JiaqingChen/ViT-models/VIT_model_seed_2023_threshold_{100}.pt' --data '/global/cfs/cdirs/m636/geshi/data' --output '/global/cfs/cdirs/m636/geniesse/Vit_loss_lens' --hessian --corrupted --batch 512 --seed 2023 --device 0 --distance 3 --steps 40 --norm layer --random normal

